### ISSUE TITLE
Database & Models

### ISSUE THREAD

**Issue by Jordan-Lin** [2JLTK/starter-todo#1]
Link for task description:
[tasks](http://comp4711.jlparry.com/display/tutorial/ci-todo01)

- [x] A. Setup Development environment

- [x] B. Setup your database

- [x] C. Enable database access in your app

- [x] D. Safe Collaboration

- [x] E. Now we can configure our database access in CI

- [x] F. Add some models

- [x] G. Pre-load the models

**Comment by luxesassin** [comment]
Please check my pull request that I have done with this issue.
